SELECT PRODUCT_ID, PRODUCT_NAME FROM (PRODUCT NATURAL JOIN SALES) WHERE SALE_DATE >= TO_DATE('2019-01-01', 'YYYY-MM-DD') OR SALE_DATE <= TO_DATE('2019-03-31', 'YYYY-MM-DD')

MINUS

SELECT PRODUCT_ID, PRODUCT_NAME FROM (PRODUCT NATURAL JOIN SALES) WHERE SALE_DATE < TO_DATE('2019-01-01', 'YYYY-MM-DD') OR SALE_DATE > TO_DATE('2019-03-31', 'YYYY-MM-DD')
