SELECT
    to_char(activity_DAte, 'YYYY-MM-DD') as day,
    COUNT(DISTINCT USER_ID) as active_users
FROM
    ACTIVITY
WHERE
ACTIVITY_DATE BETWEEN TO_DATE('2019-07-27','YYYY-MM-DD') - 29 AND TO_DATE('2019-07-27', 'YYYY-MM-DD')
GROUP BY
    ACTIVITY_DATE;
