SELECT DISTINCT PAGE_ID as recommended_page FROM LIKES WHERE USER_ID IN ((SELECT USER1_ID FROM FRIENDSHIP WHERE USER2_ID = 1) UNION (SELECT USER2_ID FROM FRIENDSHIP WHERE USER1_ID = 1))

MINUS

SELECT PAGE_ID FROM LIKES WHERE USER_ID = 1
