SELECT NAME AS RESULTS FROM (SELECT NAME
FROM (MOVIERATING NATURAL JOIN USERS)
GROUP BY NAME ORDER BY COUNT(*) DESC, NAME ASC) WHERE ROWNUM = 1
UNION ALL
SELECT TITLE AS RESULTS FROM (SELECT TITLE, AVG(RATING) 
FROM (MOVIERATING NATURAL JOIN MOVIES) 
WHERE TO_CHAR(CREATED_AT, 'YYYY-MM') = '2020-02'
GROUP BY TITLE ORDER BY AVG(RATING) DESC, TITLE ASC) WHERE ROWNUM = 1;