SELECT LEFT_OPERAND, OPERATOR, RIGHT_OPERAND, 
CASE 
 WHEN OPERATOR = '>' AND LEFT_VALUE > RIGHT_VALUE THEN 'true'
 WHEN OPERATOR = '<' AND LEFT_VALUE < RIGHT_VALUE THEN 'true'
 WHEN OPERATOR = '=' AND LEFT_VALUE = RIGHT_VALUE THEN 'true'
 ELSE 'false'
 END
  AS VALUE
 
 FROM 
 (SELECT LEFT_OPERAND, RIGHT_OPERAND, OPERATOR, (SELECT VALUE FROM VARIABLES WHERE NAME = LEFT_OPERAND) AS LEFT_VALUE , (SELECT VALUE FROM VARIABLES WHERE NAME = RIGHT_OPERAND) AS RIGHT_VALUE FROM EXPRESSIONS)