SELECT COUNT(*) as accounts_count FROM (SELECT ACCOUNT_ID FROM SUBSCRIPTIONS WHERE (TO_CHAR(START_DATE, 'YYYY') = '2021' OR TO_CHAR(END_DATE, 'YYYY') = '2021')
MINUS
SELECT ACCOUNT_ID FROM STREAMS WHERE TO_CHAR(STREAM_DATE, 'YYYY') = '2021')