SELECT airport_id FROM 
(
    SELECT DEPARTURE_AIRPORT AS airport_id 
    FROM FLIGHTS
        UNION 
        SELECT ARRIVAL_AIRPORT 
        FROM FLIGHTS) 
        GROUP BY AIRPORT_ID 
        HAVING (SELECT SUM(FLIGHTS_COUNT) 
               FROM FLIGHTS 
               WHERE DEPARTURE_AIRPORT = AIRPORT_ID OR ARRIVAL_AIRPORT = AIRPORT_ID) = 
(SELECT MAX(TRAFFIC) FROM (SELECT (SELECT SUM(FLIGHTS_COUNT) FROM FLIGHTS WHERE DEPARTURE_AIRPORT = AIRPORT_ID OR ARRIVAL_AIRPORT = AIRPORT_ID) AS TRAFFIC

FROM 
(
    SELECT DEPARTURE_AIRPORT AS airport_id 
    FROM FLIGHTS
        UNION 
        SELECT ARRIVAL_AIRPORT 
        FROM FLIGHTS
)))