SELECT ROUND((SELECT COUNT(*) FROM (SELECT DISTINCT REQUESTER_ID, ACCEPTER_ID FROM REQUESTACCEPTED))/
(CASE WHEN 
(SELECT COUNT(*) FROM (SELECT DISTINCT SENDER_ID, SEND_TO_ID FROM FRIENDREQUEST)) != 0 THEN (SELECT COUNT(*) FROM (SELECT DISTINCT SENDER_ID, SEND_TO_ID FROM FRIENDREQUEST)) ELSE 1 END), 2) AS ACCEPT_RATE
FROM DUAL